/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-10-23 18:19:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ActualizarCliente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Actualizar Cliente</title>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"estilos/registro.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");

        String id = request.getParameter("id");
        String nombre = request.getParameter("nom");
        String apellido = request.getParameter("ape");
        String email = request.getParameter("email");
        String dni = request.getParameter("dni");
        String telefono = request.getParameter("telf");
    
      out.write("\r\n");
      out.write("    <h1>Actualizar Cliente</h1>\r\n");
      out.write("    <div class=\"box-registro\">\r\n");
      out.write("        <form action=\"ControladorCliente\" method=\"post\">\r\n");
      out.write("            <!-- Campo oculto para el ID -->\r\n");
      out.write("            <input type=\"hidden\" name=\"id\" value=\"");
      out.print(id);
      out.write("\">\r\n");
      out.write("            \r\n");
      out.write("            <label for=\"nombre\">Nombre:</label>\r\n");
      out.write("            <input type=\"text\" id=\"nombre\" name=\"nom\" value=\"");
      out.print(nombre);
      out.write("\" required>\r\n");
      out.write("            \r\n");
      out.write("            <label for=\"apellido\">Apellido:</label>\r\n");
      out.write("            <input type=\"text\" id=\"apellido\" name=\"ape\" value=\"");
      out.print(apellido);
      out.write("\" required>\r\n");
      out.write("            \r\n");
      out.write("            <label for=\"email\">Email:</label>\r\n");
      out.write("            <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.print(email);
      out.write("\" required>\r\n");
      out.write("            \r\n");
      out.write("            <label for=\"dni\">DNI:</label>\r\n");
      out.write("            <input type=\"text\" id=\"dni\" name=\"dni\" value=\"");
      out.print(dni);
      out.write("\" required>\r\n");
      out.write("            \r\n");
      out.write("            <label for=\"telefono\">Teléfono:</label>\r\n");
      out.write("            <input type=\"tel\" id=\"telefono\" name=\"telf\" value=\"");
      out.print(telefono);
      out.write("\" required>\r\n");
      out.write("            \r\n");
      out.write("            <button type=\"submit\">Actualizar</button>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Botón opcional para cancelar y volver al listado -->\r\n");
      out.write("            <a href=\"ControladorCliente?accion=Listar\" style=\"\r\n");
      out.write("                display: block;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-top: 10px;\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("                background-color: #f44336;\r\n");
      out.write("                color: white;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("            \">Cancelar</a>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
