/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-10-23 04:26:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.Cliente;
import model.Habitacion;
import Dao.ClassClienteImp;
import Dao.ClassHabitacionImp;

public final class ActualizarReserva_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Actualizar Reserva</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"estilos/registro.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1 align=\"center\">Actualizar Reserva</h1>\r\n");
      out.write("\r\n");
      out.write("<form action=\"ControladorReserva\" method=\"post\">\r\n");
      out.write("    ");

    String idReserva = (request.getAttribute("idReserva") != null) ? request.getAttribute("idReserva").toString() : "";
    String idCliente = (request.getAttribute("idCliente") != null) ? request.getAttribute("idCliente").toString() : "";
    String idHabitacion = (request.getAttribute("idHabitacion") != null) ? request.getAttribute("idHabitacion").toString() : "";
    String fechaInicio = (request.getAttribute("fechaInicio") != null) ? request.getAttribute("fechaInicio").toString() : "";
    String fechaFin = (request.getAttribute("fechaFin") != null) ? request.getAttribute("fechaFin").toString() : "";
    
      out.write("\r\n");
      out.write("    <table border=\"2\" align=\"center\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>ID RESERVA</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"idReserva\" value=\"");
      out.print( idReserva );
      out.write("\" readonly></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>Cliente</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <select name=\"idCliente\" required>\r\n");
      out.write("                    <option value=\"\">Seleccione el Cliente</option>\r\n");
      out.write("                ");

                ClassClienteImp clienteDAO = new ClassClienteImp();
                List<Cliente> clientes = clienteDAO.listaCliente();
                for(Cliente cliente: clientes){
                
      out.write("\r\n");
      out.write("                    <option value=\"");
      out.print(cliente.getID_Cliente());
      out.write('"');
      out.write('>');
      out.print(cliente.getNombreC());
      out.write("</option>\r\n");
      out.write("                ");

                        }
                
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>Habitación</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <select name=\"idHabitacion\" required>\r\n");
      out.write("                    <option value=\"\">Seleccione el habitacion</option>\r\n");
      out.write("                ");

                ClassHabitacionImp habitacionDAO = new ClassHabitacionImp();
                List<Habitacion> habitaciones = habitacionDAO.listaHabitacion();
                for(Habitacion habitacion: habitaciones){
                
      out.write("\r\n");
      out.write("                    <option value=\"");
      out.print(habitacion.getID_Habitacion());
      out.write('"');
      out.write('>');
      out.print(habitacion.getID_Habitacion());
      out.write("</option>\r\n");
      out.write("                ");

                        }
                
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>Fecha Inicio</td>\r\n");
      out.write("            <td><input type=\"date\" name=\"fechaInicio\" value=\"");
      out.print( fechaInicio );
      out.write("\" required></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>Fecha Fin</td>\r\n");
      out.write("            <td><input type=\"date\" name=\"fechaFin\" value=\"");
      out.print( fechaFin );
      out.write("\" required></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"2\" align=\"center\"><input type=\"submit\" value=\"Actualizar Reserva\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
