/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-10-23 18:38:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.Cliente;

public final class ListadoClientes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>GESTIONES</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"estilos/lis-habitacion.css\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    height: 100vh;\r\n");
      out.write("    background-color: #121212;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contenedor {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    width: 90%;\r\n");
      out.write("    max-width: 1600px;\r\n");
      out.write("    box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".izqUsuario {\r\n");
      out.write("    background-color: #1e1e1e;\r\n");
      out.write("    width: 30%;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imgUsu-nameUsu {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imgUsu-nameUsu img {\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imgUsu-nameUsu h2 {\r\n");
      out.write("    color: #ffcc00;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".actionsUsu a, .listados a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 300px;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    margin: 10px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    background-color: #ffcc00;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".actionsUsu a:hover, .listados a:hover {\r\n");
      out.write("    background-color: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".derAcciones {\r\n");
      out.write("    background-color: #2e2e2e;\r\n");
      out.write("    width: 70%;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    justify-content: flex-start;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".listados {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: row;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".listado-clientes {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    min-width: 600px;\r\n");
      out.write("    background-color: #3e3e3e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("    padding: 12px 15px;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("    background-color: #ffcc00;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-editar, .btn-eliminar {\r\n");
      out.write("    padding: 8px 12px;\r\n");
      out.write("    margin-right: 5px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-editar {\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: rgb(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-eliminar {\r\n");
      out.write("    background-color: #f44336;\r\n");
      out.write("    color: rgb(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-editar:hover, .btn-eliminar:hover {\r\n");
      out.write("    opacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"contenedor\">\r\n");
      out.write("        <div class=\"izqUsuario\">\r\n");
      out.write("            <div class=\"imgUsu-nameUsu\">\r\n");
      out.write("                <img src=\"images/usuario.1.png\" alt=\"Usuario\" width=\"200px\">\r\n");
      out.write("                <h2>Usuario: Kevin Quintero</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"actionsUsu\">\r\n");
      out.write("                <a href=\"RegistroReserva.jsp\">Registrar Reserva</a> \r\n");
      out.write("                <a href=\"RegistroCliente.jsp\">Registrar Cliente</a> \r\n");
      out.write("                <a href=\"RegistroHabitacion.jsp\">Registrar Habitación</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"derAcciones\">\r\n");
      out.write("            <div class=\"listados\">\r\n");
      out.write("                <a href=\"ControladorReserva?accion=Listar\">Listado de Reservas</a> \r\n");
      out.write("                <a href=\"ControladorCliente?accion=Listar\">Listado de Clientes</a> \r\n");
      out.write("                <a href=\"ControladorHabitacion?accion=Listar\">Listado de Habitaciones</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"listado-clientes\">\r\n");
      out.write("                <h1>Listado de clientes</h1>\r\n");
      out.write("                <table border=\"2\" align=\"center\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>ID</th>\r\n");
      out.write("                            <th>Nombre</th>\r\n");
      out.write("                            <th>Apellido</th>\r\n");
      out.write("                            <th>Email</th>\r\n");
      out.write("                            <th>DNI</th>\r\n");
      out.write("                            <th>Teléfono</th>\r\n");
      out.write("                            <th colspan=\"2\" align=\"center\">Acciones</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");

                        List<Cliente> listadoClientes = (List<Cliente>)request.getAttribute("listadoClientes");
                        if (listadoClientes != null && !listadoClientes.isEmpty()) {
                            for (Cliente cliente : listadoClientes) {
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print(cliente.getID_Cliente());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(cliente.getNombreC());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(cliente.getApellidoC());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(cliente.getEmail());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(cliente.getDni());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(cliente.getTelefono());
      out.write("</td>\r\n");
      out.write("                            <td><a class=\"btn-eliminar\" href=\"ControladorCliente?accion=Eliminar&id=");
      out.print(cliente.getID_Cliente());
      out.write("\">Eliminar</a></td>\r\n");
      out.write("                            <td><a class=\"btn-editar\" href=\"ActualizarCliente.jsp?id=");
      out.print(cliente.getID_Cliente());
      out.write("&nom=");
      out.print(cliente.getNombreC());
      out.write("&ape=");
      out.print(cliente.getApellidoC());
      out.write("&email=");
      out.print(cliente.getEmail());
      out.write("&dni=");
      out.print(cliente.getDni());
      out.write("&telf=");
      out.print(cliente.getTelefono());
      out.write("\">Actualizar</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");

                        }
                        } else {
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"8\" align=\"center\">No hay clientes registrados</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");

                        }
                        
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
