/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-10-23 18:38:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.Habitacion;

public final class ListadoHabitaciones_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Listado de Habitaciones</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"estilos/lis-habitacion.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: Arial, sans-serif;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\theight: 100vh;\r\n");
      out.write("\tbackground-color: #121212;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contenedor {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\tmax-width: 1600px;\r\n");
      out.write("\tbox-shadow: 0 0 20px rgba(0, 0, 0, 0.5);\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".izqUsuario {\r\n");
      out.write("\tbackground-color: #1e1e1e;\r\n");
      out.write("\twidth: 30%;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imgUsu-nameUsu {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imgUsu-nameUsu img {\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imgUsu-nameUsu h2 {\r\n");
      out.write("\tcolor: #ffcc00;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".actionsUsu a, .listados a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmax-width: 300px;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tmargin: 10px 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tbackground-color: #ffcc00;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\ttransition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".actionsUsu a:hover, .listados a:hover {\r\n");
      out.write("\tbackground-color: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".derAcciones {\r\n");
      out.write("\tbackground-color: #2e2e2e;\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\tjustify-content: flex-start;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".listados {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: row;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tgap: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".listado-clientes {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmargin-top: 0;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\tgap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tmin-width: 600px;\r\n");
      out.write("\tbackground-color: #3e3e3e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("\tpadding: 12px 15px;\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("\tbackground-color: #ffcc00;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-editar, .btn-eliminar {\r\n");
      out.write("\tpadding: 8px 12px;\r\n");
      out.write("\tmargin-right: 5px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\ttransition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-editar {\r\n");
      out.write("\tbackground-color: #4CAF50;\r\n");
      out.write("\tcolor: rgb(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-eliminar {\r\n");
      out.write("\tbackground-color: #f44336;\r\n");
      out.write("\tcolor: rgb(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-editar:hover, .btn-eliminar:hover {\r\n");
      out.write("\topacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"contenedor\">\r\n");
      out.write("\t\t<div class=\"izqUsuario\">\r\n");
      out.write("\t\t\t<div class=\"imgUsu-nameUsu\">\r\n");
      out.write("\t\t\t\t<img src=\"images/usuario.1.png\" alt=\"Usuario\" width=\"200px\">\r\n");
      out.write("\t\t\t\t<h2>Usuario: Kevin Quintero</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"actionsUsu\">\r\n");
      out.write("\t\t\t\t<a href=\"RegistroReserva.jsp\">Registrar Reserva</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"RegistroCliente.jsp\">Registrar Cliente</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"RegistroHabitacion.jsp\">Registrar Habitación</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"derAcciones\">\r\n");
      out.write("\t\t\t<div class=\"listados\">\r\n");
      out.write("\t\t\t\t<a href=\"ControladorReserva?accion=Listar\">Listado de Reservas</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"ControladorCliente?accion=Listar\">Listado de Clientes</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"ControladorHabitacion?accion=Listar\">Listado de\r\n");
      out.write("\t\t\t\t\tHabitaciones</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"listado-habitaciones\">\r\n");
      out.write("\t\t\t\t<h1>Listado de Habitaciones</h1>\r\n");
      out.write("\t\t\t\t<table border=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>ID Habitación</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Tipo de Habitación</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Precio</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Comodidades</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Estado</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th colspan=\"2\" align=\"center\">Acciones</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");

						List<Habitacion> listadoHabitaciones = (List<Habitacion>) request.getAttribute("listadoHabitaciones");
						if (listadoHabitaciones != null && !listadoHabitaciones.isEmpty()) {
							for (Habitacion habitacion : listadoHabitaciones) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(habitacion.getID_Habitacion());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(habitacion.getTipohabitacion().getNom_TipoH());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(habitacion.getPrecio());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(habitacion.getComodidades());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(habitacion.getEstadohabitacion().getNom_EstadoH());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class=\"btn-eliminar\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"ControladorHabitacion?accion=Eliminar&id=");
      out.print(habitacion.getID_Habitacion());
      out.write("\">Eliminar</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("    <a class=\"btn-editar\" href=\"ControladorHabitacion?accion=Actualizar&action=show&id=");
      out.print(habitacion.getID_Habitacion());
      out.write("\">Actualizar</a>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"7\" align=\"center\">No hay habitaciones\r\n");
      out.write("\t\t\t\t\t\t\t\tregistradas</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
